# This is a basic workflow to build the app

name: Build
run-name: ¡Build App!

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "prettier"
  prettier:
    # Define a time-out flow
    timeout-minutes: 15
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.11.1

      # Get npm cache directory
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      # 1) Install dependencies
      - name: Install dependencies
        run: npm i

      # 2) Run prettier
      - name: Prettier
        run: npm run prettier-check

  # This workflow contains a single job called "lint"
  lint:
    # Define a time-out flow
    timeout-minutes: 15
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.11.1

      # Get npm cache directory
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      # 1) Install dependencies
      - name: Install dependencies
        run: npm i

      # 2) Run lint
      - name: Lint
        run: npm run lint

  # This workflow contains a single job called "stylelint"
  stylelint:
    # Define a time-out flow
    timeout-minutes: 15
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.11.1

      # Get npm cache directory
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      # 1) Install dependencies
      - name: Install dependencies
        run: npm i

      # 2) Run stylelint
      - name: Stylelint
        run: npm run stylelint

  # This workflow contains a single job called "build"
  build:
    # Define a time-out flow
    timeout-minutes: 15
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: PUBLIC_ENVIRONMENTS
    env:
      PUBLIC_AUTHOR_NAME: ${{ vars.PUBLIC_COMPANY_NAME }}
      PUBLIC_PAGE_URL: ${{ vars.PUBLIC_COMPANY_NAME }}
      PUBLIC_COMPANY_NAME: ${{ vars.PUBLIC_COMPANY_NAME }}
      PUBLIC_COMPANY_EMAIL: ${{ vars.PUBLIC_COMPANY_EMAIL }}
      PUBLIC_COMPANY_PHONE: ${{ vars.PUBLIC_COMPANY_PHONE }}
      PUBLIC_COMPANY_LINKEDIN: ${{ vars.PUBLIC_COMPANY_LINKEDIN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify environment variables
        run: |
          echo "PUBLIC_COMPANY_NAME: ${PUBLIC_AUTHOR_NAME}"
          echo "PUBLIC_COMPANY_NAME: ${PUBLIC_PAGE_URL}"
          echo "PUBLIC_COMPANY_NAME: ${PUBLIC_COMPANY_NAME}"
          echo "PUBLIC_COMPANY_EMAIL: ${PUBLIC_COMPANY_EMAIL}"
          echo "PUBLIC_COMPANY_PHONE: ${PUBLIC_COMPANY_PHONE}"
          echo "PUBLIC_COMPANY_LINKEDIN: ${PUBLIC_COMPANY_LINKEDIN}"

      # Runs a setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.11.1

      # Get npm cache directory
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      # 1) Install dependencies
      - name: Install dependencies
        run: npm i

      # 2) Run build test
      - name: Build
        run: npm run build
